# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 33d76ac83c730916aaeefa6c4f32b37ca7e449feac0bf7c8137b77d78460ebe9e6652bdc5134fe55b7c18fc3c8f78f510e224f38873ef5da7d515122ace1887f

test:
  secret_key_base: 9663fed0a75d82dda3bac031c3629d31f99a844f2e693c70b6f1c3a1f0b60dd006e2d7b9b897627d62d29aff576577341cda497141cc51126a0a4e52427653a2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
